// Code generated by "stringer -type=TemperatureUnitType"; DO NOT EDIT.

package worrywort

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FAHRENHEIT-0]
	_ = x[CELSIUS-1]
}

const _TemperatureUnitType_name = "FAHRENHEITCELSIUS"

var _TemperatureUnitType_index = [...]uint8{0, 10, 17}

func (i TemperatureUnitType) String() string {
	if i < 0 || i >= TemperatureUnitType(len(_TemperatureUnitType_index)-1) {
		return "TemperatureUnitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TemperatureUnitType_name[_TemperatureUnitType_index[i]:_TemperatureUnitType_index[i+1]]
}
