// Code generated by "stringer -type=VolumeUnitType"; DO NOT EDIT.

package worrywort

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GALLON-0]
	_ = x[QUART-1]
}

const _VolumeUnitType_name = "GALLONQUART"

var _VolumeUnitType_index = [...]uint8{0, 6, 11}

func (i VolumeUnitType) String() string {
	if i < 0 || i >= VolumeUnitType(len(_VolumeUnitType_index)-1) {
		return "VolumeUnitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VolumeUnitType_name[_VolumeUnitType_index[i]:_VolumeUnitType_index[i+1]]
}
