# Use a different base image?  This one is pretty big
FROM golang:1.9.2-stretch as base
MAINTAINER Justin Michalicek <jmichalicek@gmail.com>

RUN wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -O /go/bin/dep
# Make a dev user rather than running as root?
RUN chmod a+x /go/bin/dep
RUN mkdir -p /go/src/github.com/jmichalicek/worrywort-server-go
WORKDIR /go/src/github.com/jmichalicek/worrywort-server-go
EXPOSE 8080
VOLUME ["/go/src/github.com/jmichalicek/worrywort-server-go"]
